--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SaraiCsDev/ClaimMaster
build-by-default: true
branches:
- main
projects:
  ClaimMaster:
    path: .
    libs:
      - src
    model: default
    php:
      - '7.4'
    entry: src/Banshoku/Claims/Main.php
    class: main\MainClass
    name: ClaimMaster
    version: 1.0.0
    description: Plugin de protección de terrenos basado en chunks para PocketMine-MP.
    license: mit
    icon: icon.png
...
